{"uuid": "ba62659e-d8df-45b3-a393-f5acc49dd662", "children": ["554c6236-ad0a-47fc-baf7-41c355417d8b"], "befores": [{"name": "add_principal", "status": "broken", "statusDetails": {"message": "requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://ivanh2.neosdata.cloud/api/iam/group/UNDEFINED/principals\n", "trace": "  File \"/Users/ihur/Library/Caches/pypoetry/virtualenvs/neos-core-tests-UGE2DFwI-py3.10/lib/python3.10/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/ihur/Library/Caches/pypoetry/virtualenvs/neos-core-tests-UGE2DFwI-py3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/ihur/Library/Caches/pypoetry/virtualenvs/neos-core-tests-UGE2DFwI-py3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/ihur/Documents/qa_reps/neos-core-tests/tests/integration/api/iam/group/conftest.py\", line 70, in add_principal\n    group.add_principals_to_group(principals=PrincipalsData(principals=[new_user_data.uuid]))\n  File \"/Users/ihur/Library/Caches/pypoetry/virtualenvs/neos-core-tests-UGE2DFwI-py3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/ihur/Documents/qa_reps/neos-core-tests/harness/helpers/api/hub/iam/group.py\", line 97, in add_principals_to_group\n    response.raise_for_status()\n  File \"/Users/ihur/Library/Caches/pypoetry/virtualenvs/neos-core-tests-UGE2DFwI-py3.10/lib/python3.10/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n"}, "steps": [{"name": "Add principal to a group", "status": "broken", "statusDetails": {"message": "requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://ivanh2.neosdata.cloud/api/iam/group/UNDEFINED/principals\n", "trace": "  File \"/Users/ihur/Library/Caches/pypoetry/virtualenvs/neos-core-tests-UGE2DFwI-py3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/ihur/Documents/qa_reps/neos-core-tests/harness/helpers/api/hub/iam/group.py\", line 97, in add_principals_to_group\n    response.raise_for_status()\n  File \"/Users/ihur/Library/Caches/pypoetry/virtualenvs/neos-core-tests-UGE2DFwI-py3.10/lib/python3.10/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n"}, "parameters": [{"name": "principals", "value": "PrincipalsData(principals=['6a997816-d802-4413-98ae-5a1401c24a70'])"}], "start": 1698654783424, "stop": 1698654783540}], "start": 1698654783423, "stop": 1698654783541}], "start": 1698654783423, "stop": 1698654783570}