{"name": "test_query_cannot_be_run_when_action_denied", "status": "skipped", "statusDetails": {"message": "XFAIL Bug https://neom.atlassian.net/browse/NEOS-3266 [BE] 500 error when user without product:consume permissions tries to list products or run statement (GET powerbi/products, POST powerbi/statement)\n\nAssertionError: in 'message' field:\n\t\tActual: user has insufficient permissions \n\t\tExpected: Insufficient permissions.", "trace": "tests/integration/api/consume/powerbi/test_run_query.py:391: in test_query_cannot_be_run_when_action_denied\n    assert ApiError.from_response(response) == common_error.insufficient_permissions_error.with_debug_message_args(\nharness/api/model/error/api_error.py:53: in __eq__\n    assert other._message.startswith(self._message), _DEFAULT_MESSAGE.format(\nE   AssertionError: in 'message' field:\nE   \t\tActual: user has insufficient permissions \nE   \t\tExpected: Insufficient permissions."}, "description": "\n        As a user\n        When I have `product:consume` action denied for gateway and registry\n        And I run query\n        Then I get an error response\n        ", "attachments": [{"name": "log", "source": "a4e8ab07-1c72-4043-9a14-5f754341d9e4-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "abb1ce02-de7e-4646-9cec-eafd4aa7bc13-attachment.txt", "type": "text/plain"}], "start": 1698654835555, "stop": 1698654835618, "uuid": "485c915f-90be-4e63-9536-642698c0ffe5", "historyId": "f089e495dd21be349688c0e84a858a90", "testCaseId": "f089e495dd21be349688c0e84a858a90", "fullName": "tests.integration.api.consume.powerbi.test_run_query.TestApiRunQuery#test_query_cannot_be_run_when_action_denied", "labels": [{"name": "feature", "value": "Run query"}, {"name": "story", "value": "Query cannot be run when `product:consume` action denied for gateway and registry"}, {"name": "parentSuite", "value": "[API] ConsumeQuery"}, {"name": "tag", "value": "@pytest.mark.usefixtures('authenticate_neos_admin', 'create_product_1_v2', 'add_product_1_schema_v2', 'add_rows_to_product_1_table', 'create_data_product_v2', 'add_schema_v2', 'builder_set_product_1_as_input', 'builder_run', 'publish_data_product_v2', 'create_user', 'set_user_policy_type', 'deny_product_consume_action', 'deny_registry_product_consume_action', 'create_user_policy', 'authenticate_as_new_user')"}, {"name": "tag", "value": "@pytest.mark.xfail(reason='Bug https://neom.atlassian.net/browse/NEOS-3266 [BE] 500 error when user without product:consume permissions tries to list products or run statement (GET powerbi/products, POST powerbi/statement)')"}, {"name": "tag", "value": "access"}, {"name": "tag", "value": "negative"}, {"name": "tag", "value": "consume"}, {"name": "suite", "value": "test_run_query"}, {"name": "subSuite", "value": "TestApiRunQuery"}, {"name": "host", "value": "Is-MacBook-Pro.local"}, {"name": "thread", "value": "26202-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.integration.api.consume.powerbi.test_run_query"}]}