{"uuid": "a2c04476-c5f6-4718-b1b1-85a4511e2994", "children": ["8ce7e886-f377-4666-9b5c-756843c38c6d"], "befores": [{"name": "add_principal", "status": "broken", "statusDetails": {"message": "requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://ivanh2.neosdata.cloud/api/iam/group/UNDEFINED/principals\n", "trace": "  File \"/Users/ihur/Library/Caches/pypoetry/virtualenvs/neos-core-tests-UGE2DFwI-py3.10/lib/python3.10/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/ihur/Library/Caches/pypoetry/virtualenvs/neos-core-tests-UGE2DFwI-py3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/ihur/Library/Caches/pypoetry/virtualenvs/neos-core-tests-UGE2DFwI-py3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/ihur/Documents/qa_reps/neos-core-tests/tests/integration/api/iam/group/conftest.py\", line 70, in add_principal\n    group.add_principals_to_group(principals=PrincipalsData(principals=[new_user_data.uuid]))\n  File \"/Users/ihur/Library/Caches/pypoetry/virtualenvs/neos-core-tests-UGE2DFwI-py3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/ihur/Documents/qa_reps/neos-core-tests/harness/helpers/api/hub/iam/group.py\", line 97, in add_principals_to_group\n    response.raise_for_status()\n  File \"/Users/ihur/Library/Caches/pypoetry/virtualenvs/neos-core-tests-UGE2DFwI-py3.10/lib/python3.10/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n"}, "steps": [{"name": "Add principal to a group", "status": "broken", "statusDetails": {"message": "requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://ivanh2.neosdata.cloud/api/iam/group/UNDEFINED/principals\n", "trace": "  File \"/Users/ihur/Library/Caches/pypoetry/virtualenvs/neos-core-tests-UGE2DFwI-py3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/ihur/Documents/qa_reps/neos-core-tests/harness/helpers/api/hub/iam/group.py\", line 97, in add_principals_to_group\n    response.raise_for_status()\n  File \"/Users/ihur/Library/Caches/pypoetry/virtualenvs/neos-core-tests-UGE2DFwI-py3.10/lib/python3.10/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n"}, "parameters": [{"name": "principals", "value": "PrincipalsData(principals=['904eb6f1-92be-43e5-b0f4-beca225d7a38'])"}], "start": 1698654791249, "stop": 1698654791348}], "start": 1698654791248, "stop": 1698654791348}], "start": 1698654791248, "stop": 1698654791379}