{"uuid": "df5e6902-3374-4fa8-884e-b1a4cdce3298", "children": ["7f813652-6a07-4241-aea7-b9082c5c4790"], "befores": [{"name": "run_select_query", "status": "broken", "statusDetails": {"message": "requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://ivanh2.neosdata.cloud/api/consume/v2/powerbi/statement\n", "trace": "  File \"/Users/ihur/Library/Caches/pypoetry/virtualenvs/neos-core-tests-UGE2DFwI-py3.10/lib/python3.10/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/ihur/Library/Caches/pypoetry/virtualenvs/neos-core-tests-UGE2DFwI-py3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/ihur/Library/Caches/pypoetry/virtualenvs/neos-core-tests-UGE2DFwI-py3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/ihur/Documents/qa_reps/neos-core-tests/tests/integration/api/consume/powerbi/conftest.py\", line 18, in run_select_query\n    powerbi_query.run(query_data=new_data_product_v2.trino_table.name)\n  File \"/Users/ihur/Library/Caches/pypoetry/virtualenvs/neos-core-tests-UGE2DFwI-py3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/ihur/Documents/qa_reps/neos-core-tests/harness/helpers/api/powerbi/consume_query.py\", line 60, in run\n    response.raise_for_status()\n  File \"/Users/ihur/Library/Caches/pypoetry/virtualenvs/neos-core-tests-UGE2DFwI-py3.10/lib/python3.10/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n"}, "steps": [{"name": "Run query", "status": "broken", "statusDetails": {"message": "requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://ivanh2.neosdata.cloud/api/consume/v2/powerbi/statement\n", "trace": "  File \"/Users/ihur/Library/Caches/pypoetry/virtualenvs/neos-core-tests-UGE2DFwI-py3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/ihur/Documents/qa_reps/neos-core-tests/harness/helpers/api/powerbi/consume_query.py\", line 60, in run\n    response.raise_for_status()\n  File \"/Users/ihur/Library/Caches/pypoetry/virtualenvs/neos-core-tests-UGE2DFwI-py3.10/lib/python3.10/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n"}, "parameters": [{"name": "query_data", "value": "'iceberg.neos.\"auto_product_stored_ggxbyvcloy\"'"}], "start": 1698654775124, "stop": 1698654775191}], "start": 1698654775124, "stop": 1698654775198}], "start": 1698654775124, "stop": 1698654775508}